# Installers (ADR 0008): an NSIS installer on Windows, built with CPack from the
# installed tree. The Linux AppImage is built by linuxdeploy in CI instead.
set(CPACK_PACKAGE_NAME "Misign")
set(CPACK_PACKAGE_VENDOR "Misign")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_VERSION "${MISIGN_VERSION}")
set(CPACK_PACKAGE_HOMEPAGE_URL "${PROJECT_HOMEPAGE_URL}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Misign")
# Start menu shortcut to bin/misign.exe.
set(CPACK_PACKAGE_EXECUTABLES "misign" "Misign")
set(CPACK_PACKAGE_FILE_NAME "Misign-${MISIGN_VERSION}-windows-x64-setup")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_STRIP_FILES ON)

set(CPACK_GENERATOR "NSIS")
set(CPACK_NSIS_DISPLAY_NAME "Misign")
set(CPACK_NSIS_PACKAGE_NAME "Misign ${MISIGN_VERSION}")
set(CPACK_NSIS_URL_INFO_ABOUT "${PROJECT_HOMEPAGE_URL}")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_MODIFY_PATH OFF)
set(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\\\misign.exe")
set(CPACK_NSIS_MUI_FINISHPAGE_RUN "misign.exe")
include(CPack)
